apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-team
  annotations:
    github.com/project-slug: Ajay-Chidambaram/demo-team
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
