apiVersion: iam.aws.demo.tech/v1alpha1
kind: DBInstance
metadata:
  name: demo-team
spec:
  tableName: demo-team-table
  roleName: demo-role
  awsRegion: us-east-1
  customTags:
    key1: value1
    key2: value2
  managementPolicies:
  - Observe
  - Create
  - Update
  - Delete
  - LateInitialize
